- name: start task
  #import_tasks: site.yml
  include: site.yml
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
