#!/usr/bin/env bash
#if [ $PROJEST_NAME_JK -eq 0 ]; then
#  unset PROJEST_NAME_JK
#  NUM=`sh ${WORKSPACE}/random.sh nun 4`
#  PROJEST_NAME_JK=${PROJEST_NAME_JK:-"saturn-console-$NUM"}
#fi
#
#tee saturn-console.yaml <<- EOF
---
- hosts: ${ANSIBLE_HOST_LIST_JK}
  remote_user: sysadmin

  vars:
    CONSOLE_VERSION: ${CONSOLE_VERSION_JK}
    WORK_DIR: ${WORK_DIR_JK}
    PROJEST_NAME: ${PROJEST_NAME_JK}
    ZKADDRESSLIST: ${ZKADDRESSLIST_JK}
    NAMEANDNAMESPACE: ${NAME_AND_NAMESPACE_LIST}


  tasks:

  - set_fact:
      RANDOM_NAME: "{{ 100 | random }}"
    run_once: yes
    when: (PROJEST_NAME == 0)

  - file:
      path: "{{ WORK_DIR }}/{{ PROJEST_NAME }}"
      state: absent
 
  - file:
      path: "{{ WORK_DIR }}/{{ PROJEST_NAME }}"
      state: directory
      owner: sysadmin
      group: sysadmin
      #mode: 0755

  - copy:
      src: "saturn-console-{{ CONSOLE_VERSION }}.jar"
      dest: "{{ WORK_DIR }}/{{ PROJEST_NAME }}/saturn-console-{{ CONSOLE_VERSION }}.jar"
      owner: sysadmin
      group: sysadmin

  - template:
      src: regcenter.json.j2
      dest: "{{ WORK_DIR }}/{{ PROJEST_NAME }}/regcenter.json"
      owner: sysadmin
      group: sysadmin
      mode: 0644
      
  - name: start saturn-console-{{ CONSOLE_VERSION }}
    shell: 'nohup $(which java) -DSATURN_CONSOLE_LOG={{ WORK_DIR }}/{{ PROJEST_NAME }} \
           -DREG_CENTER_JSON_PATH={{ WORK_DIR }}/{{ PROJEST_NAME }}/regcenter.json \
           -jar {{ WORK_DIR }}/{{ PROJEST_NAME }}/saturn-console-{{ CONSOLE_VERSION }}.jar >/dev/null 2>&1 &'
      
#EOF
