---
- hosts: localhost
  remote_user: sysadmin

  vars:
    tomcat_version: "{{ tomcat_version_jk | default('8.0.49') }}"
    tomcat_native_version: "{{ tomcat_native_version_jk | default('1.2.16') }}"
    tomcat_dl_url: "{{ tomcat_dl_url_jk | default('http://192.168.30.247/t/tomcat') }}"
    tomcat_user_name: "{{ tomcat_user_name_jk | default('sysadmin')  }}"
    tomcat_group_name: "{{ tomcat_group_name_jk | default('sysadmin')  }}"
    tomcat_password: "{{ tomcat_password_jk | default('yg8AHjUjgjDl94dB')  }}"

    tomcat_base_dir: "{{ tomcat_base_dir_jk | default('/data/tomct') }}"
    tomcat_use_apr: "{{ tomcat_use_apr_jk | default(true) }}"
    tomcat_apr_dir: "{{ tomcat_base_dir }}/apr"
    tomcat_port_shutdown: "{{ tomcat_port_shutdown_jk | default('8005')}}"
    tomcat_port_connetctor: "{{ tomcat_port_connetctor_jk | default('8080')}}"
    tomcat_port_redirect: "{{ tomcat_port_redirect_jk | default('8443')}}"
    tomcat_port_ajp: "{{ tomcat_port_ajp_jk | default('8009')}}"
    tomcat_java_opts: "{{ tomcat_java_opts | default('') }}"
    tomcat_catalina_opts: "{{ tomcat_catalina_opts_jk | default('') }}"
    #tomcat_base_dir_randomn: "{{ tomcat_base_dir_randomn_jk | default('') }}"
    tomcat_setenv_sh: "{{ tomcat_setenv_sh_jk | default('false') }}"
    tomcat_tmp_dir: /tmp

    tomcat_enable_gui: "{{ tomcat_enable_gui_jk | default('true') }}"
    tomcat_roles:
      - manager
      - manager-gui
      - manager-script
      - manager-jmx
      - admin
      - admin-gui
      - admin-script 

  tasks:
    - name: install package
      yum: name={{ item }} state=present
      with_items:
      - apr
      - apr-util
      - apr-devel
      - apr-util-devel
      - openssl
      - openssl-devel

    - group:
        name: "{{ tomcat_group_name }}"
        state: present

    - user:
        name: "{{ tomcat_user_name }}" 
        group: "{{ tomcat_group_name }}"
        shell: /bin/bash
        #comment: "{{ tomcat_user_name }}"
        #uid: 1040
        #append: yes

    - set_fact:
        RANDOM_PATH: "{{ 100 | random }}"
      run_once: yes
      #when: (not tomcat_base_dir_randomn)

    - file:
        path: "{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}"
        state: directory
        mode: 0755
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
      #when: (not tomcat_base_dir_randomn)

    #- file:
    #    path: "{{ tomcat_base_dir }}/{{ tomcat_base_dir_randomn }}"
    #    state: directory
    #    mode: 0755
    #    owner: "{{ tomcat_user_name }}"
    #    group: "{{ tomcat_group_name }}"
    #  when: (tomcat_base_dir_randomn)

    - name: Download Tomcat8
      ignore_errors: True
      register: downlad_tomcat_status
      get_url:
        dest: "{{ tomcat_tmp_dir }}"
        url: "{{ item }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
      with_items: "{{ tomcat_dl_url }}"
      async: 300
      poll: 3
      tags:
        download_tomcat8

    - copy:
        src: "{{ tomcat_tmp_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_tmp_dir }}"
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"

    #- name: unarchive tomcat8
    - unarchive:
        remote_src: yes
        src: "{{ tomcat_tmp_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}"
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
        keep_newer: yes

    - name: unarchive tomcat-native.tar.gz
      when: tomcat_use_apr 
      unarchive:
        remote_src: yes
        src: "{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}/apache-tomcat-{{ tomcat_version }}/bin/tomcat-native.tar.gz"
        dest: "{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}/apache-tomcat-{{ tomcat_version }}/bin/"
        keep_newer: yes

    - name: get JAVA_HOME
      shell: 'echo $JAVA_HOME'
      register: JAVA_HOME_PATH
      when: tomcat_use_apr

    - file:
        path: "{{ tomcat_apr_dir }}"
        state: directory
        mode: 0755
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"

    - name: configure apr
      when: tomcat_use_apr
      register: tomcat_apr_configure
      ignore_errors: True
      command: >
        ./configure
        --with-apr=/usr/bin/apr-1-config
        --with-ssl
        --with-java-home={{ JAVA_HOME_PATH.stdout }}
        --prefix="{{ tomcat_apr_dir }}"
        chdir="{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}/apache-tomcat-{{ tomcat_version }}/bin/tomcat-native-{{tomcat_native_version }}-src/native"

    - make:
        chdir: "{{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}/apache-tomcat-{{ tomcat_version }}/bin/tomcat-native-{{tomcat_native_version }}-src/native"
      when: tomcat_use_apr

    - name: chekc apr
      shell: "/bin/ls {{ tomcat_base_dir }}/tomcat-{{ RANDOM_PATH }}/apache-tomcat-{{ tomcat_version }}/bin/tomcat-native-{{tomcat_native_version }}-src/native/.libs | /bin/grep -E '(libtcnative-1.la|libtcnative-1.so)'|wc -l"
      register: __no_found_apr
      when: tomcat_use_apr
      ignore_errors: True

    - template:
        src: template/apr.conf.j2
        dest: /etc/ld.so.conf.d/apr.conf
        mode: 0644
        #when: (__no_found_apr.stdout == 4 and tomcat_use_apr)

    - template:
        src: template/apr.env.sh.j2
        dest: /etc/profile.d/apr.env.sh
        mode: 0644

    - name: ldconfig apr.conf
      shell: /sbin/ldconfig /etc/ld.so.conf.d/apr.conf
      when: (__no_found_apr.stdout >= 3 and tomcat_use_apr)

    - name: source /etc/profile.d/apr.env.sh
      shell: source /etc/profile.d/apr.env.sh
      when: (__no_found_apr.stdout >= 3 and tomcat_use_apr)















